name: gdgoc_hackathon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/ChatIcon.png
    - assets/HomeIcon.png
    - assets/IconPage.png
    - assets/SearchIcon.png
    - assets/AppLogoForLogin.png
    - assets/ic-smile.png